### ISSUE TITLE
Allow tabs in YAML

### ISSUE THREAD

**Issue by somenxavier** [tonyfischetti/sake#55]
Hi,

As a user perspective, it's annoying not to be able to have a YAML file with indentation made by tabs. Can you solve it?

**Comment by kirbyfan64** [comment]
As far as I know, YAML (and therefore pyyaml...and therefore Sake) explicitly makes this illegal. Of course, theoretically, Sake could pre-process the file, replacing each tab with 4 spaces...but someone's bound to complain about letting users set a custom space count, and a can of worms just opens from there.

But I'm not this project's maintainer; I just like helping out in issues. :)

Why not use a text editor like [Howl](http://howl.io/) that auto-indents using spaces? Or even Sublime; just set it to use spaces. Gedit even lets you auto-indent, and Notepad++ lets you change it to use spaces instead of tabs.

**Comment by somenxavier** [comment]
OK. Thanks for the info, @kirbyfan64
