### ISSUE TITLE
Apparently there are targets sharing dependencies and I can't run my commands

### ISSUE THREAD

**Issue by fiatjaf** [tonyfischetti/sake#61]
> The following targets share dependencies and must be run together

That's what sake says. I don't know how to run them together. I have already grouped my formulas, but still they won't run. How am I supposed to do it?

**Comment by tonyfischetti** [comment]
You don't have to do any extra work. It's just letting you know that it's running both of them together.
Is it exhibiting behavior you don't expect. Is it not building?

**Comment by fiatjaf** [comment]
I have encountered this error again, but this time I could see that it was caused by a bad declaration of dependencies in the Sakefile.

**Comment by tonyfischetti** [comment]
Glad you were able to sort it out!

**Comment by damiendr** [comment]
I'm having a similar issue. My use case is an experimental workflow that has a few root dependencies, and then a number of leaf targets that each take 10-30 minutes to run. I was hoping to be able to run these targets selectively, but it seems that sake insists on building them all at once.

**Comment by tonyfischetti** [comment]
@damiendr So this has to do with how sake updates files marked for rebuilding and avoiding unstable states.
When a dependency's sha hash doesn't match the one stores in .shastore, all targets with that dependency are marked as "need to rebuild". If you run one of those targets, the dependency's sha hash in the .shastore is updated (so that it's congruent with the one from the actual filesystem. Once this is completed, the targets that also have this dependency are no longer "need to rebuild" because everything checks out. So allowing the target in question to run can lead to errors/unstable states.
In an unstable state, the onus of remembering which targets need to be updated is now on the user, rather that `sake` which is antithetical to the goal of the project.

I do, however, see the value in allowing this sort of behavior... it's something that I'd like, too
So we have a couple of options.... 
  - if you force run a target with shared dependencies, all of the sha hashes of the shared dependencies can be marked as `unstable` _for a particular set of targets_ and that they need to be rebuilt, even if the sha hash matches the one from the file on the filesystem
  - The `.shastore` file can switch from being "file" based, to being "target"-based. This has a number of advantages, but non-trivially changes the logic of a lot of the codebase. The advantages include: (a) if a new target is added, the target with always run next time `sake` is run, (b) when a _specific_ target successfully terminates, the output and dependency shas _of only that particular target_ can be updated_ meaning _that_ target is up to date, but the shas of the dependencies of the targets that share those dependencies will still be incongruent with the shas from the filesystem and, hence, will be marked for rebuilding.

I'm leaning towards the later. Do you have an opinion on this? Sorry if my explanation is confusing (my fault). Let me know if there's something I can clear up

**Comment by damiendr** [comment]
The latter sounds best, I agree — that's what I would expect without knowing about the internals.
